# -*- coding: utf-8 -*-
"""03_Water_Rahma_Absoh_Dwiyanti.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FxzUe92uUyCC_X2pUMJIXP4tDjDvBQ2P
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

data = pd.read_csv('https://raw.githubusercontent.com/Rietaros/kampus_merdeka/main/HRDataset_v14.csv')
data.head()

"""# Pandas Question

1. What is the minimum, median, max, and average salary for employee by Married Description and Gender.
Hints: use agg function<br>
Expected Output as below<br>
(5 Points)
"""

# 1. What is the minimum, median, max, and average salary for employee by Married Description and Gender
# Hints: use agg function
# Expected Output as below
# (5 Points)

#Answer here
df = pd.DataFrame(data)
result = df.groupby(['MaritalDesc', 'Sex'])['Salary'].agg(['min', 'median', 'max', 'mean']).reset_index()
result.columns = ['MaritalDesc', 'Sex', 'min_salary', 'median_salary', 'max_salary', 'average_salary']
print(result)

"""2. What is top-5 reason of termination?<br>
Expected Output as below<br>
(5 Points)
"""

#code here

#Answer here
termination_counts = df['TermReason'].value_counts().reset_index()
termination_counts.columns = ['TermReason', 'total_termination']
top_5_termination_reasons = termination_counts.head(5)
print(top_5_termination_reasons)

"""3. What is the highest number of employee by Recruitment Source that 'Exceeds' the Performance Score?
Hints: Use filter for Performance Score first. Don't forget to sort_values.<br>
Expected Output as below<br>
(5 Points)
"""

#code here

#Answer Here
filtered_df = df[df['PerformanceScore'] == 'Exceeds']
result = filtered_df['RecruitmentSource'].value_counts().reset_index()
result.columns = ['RecruitmentSource', 'total_recruit']
result = result.sort_values(by='total_recruit', ascending=False)
print(result)

"""4. How many managers in each department?
Hints: use nunique() as aggregation function.<br>
Expected Output as below.<br>
(5 Points)
"""

#code here

#Answer Here
manager_count_by_department = df.groupby('Department')['ManagerName'].nunique().reset_index()
manager_count_by_department.columns = ['Department', 'ManagerCount']
print(manager_count_by_department)

"""5. What is Termination Ratio by Gender?.
Hints: use value_counts(normalize=True).<br>
Expected Output as below.<br>
(5 Points)
"""

#code here

#Answer Here
termination_ratio_by_gender = df['Termd'].groupby(df['Sex']).value_counts(normalize=True)
print(termination_ratio_by_gender)

"""# Create an EDA and Data Visualization Question"""

#Sample Visualization, the example is not counted for the final score :p
#Create 5 visualization for better understanding on data
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np

#Ratio termination by Gender

#Step1, get the data

term = data.groupby(by=['Sex'])\
                        .agg(total_termination=('Termd','sum')).reset_index()\

#Step2, Plot it
f, ax = plt.subplots(1, 1, figsize=(12, 8))
ax = sns.barplot(x='Sex', y='total_termination', hue='Sex', data=term, palette='cool')

"""6. Buatlah Scatter plot antara kolom "Salary" dengan "EngagementSurvey", beri warna berbeda sesuai dengan status di "Termd"<br>
(5 points)<br>
*bentuk output di bawah hanya contoh*
"""

sns.scatterplot(data=data, x = 'Salary', y = 'EngagementSurvey', hue = 'Termd' )
plt.show()

"""7. Buatlah visualisasi barchart untuk menghitung jumlah "termination of an employee's" berdasarkan department.<br>
(5 points)<br>
*bentuk output di bawah hanya contoh*
"""

#answer here
term1 = data.groupby(by=['Department']).agg({'Termd':'sum'}).sort_values('Termd',ascending=False).reset_index()

f, ax = plt.subplots(1, 1, figsize = (12,8))
ax = sns.barplot(x ='Termd', y = 'Department', hue = 'Department', data=term1)

"""8. Buatlah visualisasi Pie Chart untuk melihat persentasi jumlah karyawan yang "terminated" berdasarkan kolom "Position".<br>
(5 points)<br>
*bentuk output di bawah hanya contoh*
"""

#code here
raw_data = data.loc[(data.Termd == 1)]
filterdata = raw_data.groupby('Position').count().\
sort_values(by='Termd', ascending = True).reset_index()


plt.pie(filterdata['Termd'],labels=filterdata['Position'],autopct='%1.1f%%', counterclock=False)
plt.show()

"""9. Buat Boxplot yang menggambarkan Salary berdasarkan Marital Desc, bedakan berdasarkan Termd
(5 points)
"""

sns.boxplot(data=data, x = 'Salary', y = 'MaritalDesc', hue = 'Termd')
plt.show

"""10. Tampilkan pairplot antara kolom 'Salary', 'EngagementSurvey', 'EmpSatisfaction','Absences'
beri kategori warna berdasarkan 'Termd'<br>
(5points)
"""

#codde here
print('Pairplot')
sns.pairplot(data=data[['Salary', 'EngagementSurvey', 'EmpSatisfaction','Absences', 'Termd']], hue='Termd', height=3, diag_kind="hist")
plt.show()

"""# Create Machine Learning Model to Predict Termd and Question"""

#11. Buat fitur baru (kolom baru) berupa "Age" dalam satuan tahun. Untuk mendapatkannya, ambil data pada kolom DOB dikurangi dengan 2022
#(5 points)

#Answer Here
df['DOB_date'] = pd.to_datetime(df['DOB'], format='%m/%d/%y')
df['Age'] = 2022 - df['DOB_date'].dt.year
print(df[['DOB', 'DOB_date', 'Age']])

#12. Lakukan MinMaxScaler dari fitur "Salary"
# (5 points)
from sklearn.preprocessing import MinMaxScaler

from sklearn.preprocessing import MinMaxScaler
data = df[['Salary']]
scaler = MinMaxScaler()
df['Salary_minmax'] = scaler.fit_transform(data)
print(df[['Salary', 'Salary_minmax']])

#13. Ubahlah semua tipe data object menjadi category
# 5 point

#Setelah diubah category

#13 Answer here
object_columns = ['Employee_Name', 'Position', 'State', 'DOB', 'Sex', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino',
                  'RaceDesc', 'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus', 'Department',
                  'ManagerName', 'RecruitmentSource', 'PerformanceScore', 'LastPerformanceReview_Date']
df[object_columns] = df[object_columns].astype('category')
print(df.dtypes)

#14. Ubahlah "RecruitmentSource" dengan menggunakana Label Encoder
# 5 point

#15. Ubahlah "PerformanceScore" dengan menggunakana Label Encoder
# 5 point
from sklearn.preprocessing import LabelEncoder

#16. Pisahkan dependent variable dan independent variable
# 5 point

#Dependent Varible (target)


#Independent Variable (feature)

#17. Bagi data menjadi Train-Test sebesar 80:20
# (5 points)
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_curve, roc_curve, precision_score, recall_score

#18. Lakukan pemodelan machine learning (metode klasifikasi bebas) untuk bisa memprediksi status "Termd". Lakukan evaluasi hasil dengan menampilkan
# score klasifikasi, precision dan recall.
# Gunakan model yang menurut kalian terbaik
# (5 points)

"""# Insight (Answering the Question)

19.	Is there any relationship between who a person works for (their manager) and their performance score? (5 points)<br>
20.	What are our best recruiting sources if we want to ensure a low ratio of termination? (5 points)<br>
"""



"""19. Menurut saya penilaian kerja menjadikan menjadi acuan bagi seseorang yang bekerja untuk orang lain (manajer mereka). Semakin mereka termotivasi untuk mendapatkan penilaian kinerja yang baik, maka akan semakin meningkat pula kinerja yang mereka kerjakan. Outputnya adalah nilai perusahaan akan menjadi meningkat ketika para pekerjanya bekerja sesuai dengan target atau goals yang diinginkan oleh perusahaan tersebut. Namun, perlu diingat penilaian kerja ini juga harus bersifat objektif yaitu tidak terdistorsi oleh bias, harus berdasarkan fakta, tidak emosi atau berprasangka serta mempertimbangkan fakta daripada perasaan pribadi.
20. Rekrutmen bisa dilakukan dengan dua metode yaitu metode rekrutmen internal dan metode rekrutmen eksternal. Penyebaran infromasi lowongan pekerjaan bisa melalui iklan, rekomendasi dari internal perusahaan, Perusahaan Penyedia Tenaga Kerja. Namun dari beberapa metode tersebut pasti memiliki kekurangan dan kelebihannya sendiri. Untuk itu apapun cara yang akan dipakai harus memperhatikan beberapa hal berikut :
a. Menghitung rasio terminasi, berapa karyawan yang keluar untuk setiap sumber rekrutmen.
b. Sorting : Urutkan sumber rekrutmen berdasarkan rasio terminasi yang paling rendah ke paling tinggi.
c. Evaluasi Kualitas
d. Analisis tambahan, seperti melihat berapa lama karyawan yang direkrut tetap bekerja dalam perusahaan
e. Kebijakan rekrutmen : Dapat beruppa peningkatan strategi perekrutan, pengoptimalan proses seleksi atau peningkatan dukungan dan pengembangan untuk karyawan ang direkrut dari sumber tersebut.

"""

